/* eslint-disable @typescript-eslint/no-loss-of-precision */
import { composeGid } from '@shopify/admin-graphql-api-utilities';
import { DEFAULT_ITEMS } from '../../commonDataMutation';

export const notSynqsellProductUpdateEvent = {
    version: '0',
    id: 'abcd1234-5678-90ef-gh12-3456789ijklm',
    'detail-type': 'Shopify Topic',
    source: 'shopify.com/webhooks',
    account: '123456789012',
    time: '2023-08-15T12:34:56Z',
    region: 'us-east-1',
    resources: [],
    detail: {
        'X-Shopify-Topic': 'products/update',
        'X-Shopify-Hmac-Sha256': 'hmac_value',
        'X-Shopify-Shop-Domain': 'example.myshopify.com',
        'X-Shopify-Webhook-Id': 'webhook_id',
        'X-Shopify-Triggered-At': '2024-08-15T12:34:56Z',
        'X-Shopify-Event-Id': 'event_id',
        payload: {
            admin_graphql_api_id: 'gid://shopify/Product/788032119674292922',
            body_html: 'An example T-Shirt',
            created_at: null,
            handle: 'example-t-shirt',
            id: 788032119674292922,
            product_type: 'Shirts',
            published_at: '2021-12-31T19:00:00-05:00',
            template_suffix: null,
            title: 'Example T-Shirt',
            updated_at: '2021-12-31T19:00:00-05:00',
            vendor: 'Acme',
            status: 'active',
            published_scope: 'web',
            tags: 'example, mens, t-shirt',
            variants: [
                {
                    admin_graphql_api_id: 'gid://shopify/ProductVariant/642667041472713922',
                    barcode: null,
                    compare_at_price: '24.99',
                    created_at: '2021-12-29T19:00:00-05:00',
                    id: 642667041472713922,
                    inventory_policy: 'deny',
                    position: 1,
                    price: '19.99',
                    product_id: 788032119674292922,
                    sku: null,
                    taxable: true,
                    title: 'Small',
                    updated_at: '2021-12-30T19:00:00-05:00',
                    option1: 'Small',
                    option2: null,
                    option3: null,
                    image_id: null,
                    inventory_item_id: null,
                    inventory_quantity: 75,
                    old_inventory_quantity: 75,
                },
                {
                    admin_graphql_api_id: 'gid://shopify/ProductVariant/757650484644203962',
                    barcode: null,
                    compare_at_price: '24.99',
                    created_at: '2021-12-29T19:00:00-05:00',
                    id: 757650484644203962,
                    inventory_policy: 'deny',
                    position: 2,
                    price: '19.99',
                    product_id: 788032119674292922,
                    sku: null,
                    taxable: true,
                    title: 'Medium',
                    updated_at: '2021-12-31T19:00:00-05:00',
                    option1: 'Medium',
                    option2: null,
                    option3: null,
                    image_id: null,
                    inventory_item_id: null,
                    inventory_quantity: 50,
                    old_inventory_quantity: 50,
                },
            ],
            options: [],
            images: [],
            image: null,
            media: [],
            variant_gids: [
                {
                    admin_graphql_api_id: 'gid://shopify/ProductVariant/757650484644203962',
                    updated_at: '2022-01-01T00:00:00.000Z',
                },
                {
                    admin_graphql_api_id: 'gid://shopify/ProductVariant/642667041472713922',
                    updated_at: '2021-12-31T00:00:00.000Z',
                },
            ],
        },
    },
};

export const getSupplierProductUpdateEvent = (retailPrice: string, newInventory: number) => {
    return {
        version: '0',
        id: 'abcd1234-5678-90ef-gh12-3456789ijklm',
        'detail-type': 'Shopify Topic',
        source: 'shopify.com/webhooks',
        account: '123456789012',
        time: '2023-08-15T12:34:56Z',
        region: 'us-east-1',
        resources: [],
        detail: {
            'X-Shopify-Topic': 'products/update',
            'X-Shopify-Hmac-Sha256': 'hmac_value',
            'X-Shopify-Shop-Domain': 'example.myshopify.com',
            'X-Shopify-Webhook-Id': 'webhook_id',
            'X-Shopify-Triggered-At': '2024-08-15T12:34:56Z',
            'X-Shopify-Event-Id': 'event_id',
            payload: {
                admin_graphql_api_id: composeGid('Product', DEFAULT_ITEMS.SHOPIFY_PRODUCT_ID),
                body_html: 'An example T-Shirt',
                created_at: null,
                handle: 'example-t-shirt',
                id: DEFAULT_ITEMS.SHOPIFY_PRODUCT_ID,
                product_type: 'Shirts',
                published_at: '2021-12-31T19:00:00-05:00',
                template_suffix: null,
                title: 'Example T-Shirt',
                updated_at: '2021-12-31T19:00:00-05:00',
                vendor: 'Acme',
                status: 'active',
                published_scope: 'web',
                tags: 'example, mens, t-shirt',
                variants: [
                    {
                        admin_graphql_api_id: composeGid('ProductVariant', DEFAULT_ITEMS.SHOPIFY_VARIANT_ID),
                        barcode: null,
                        compare_at_price: '24.99',
                        created_at: '2021-12-29T19:00:00-05:00',
                        id: DEFAULT_ITEMS.SHOPIFY_VARIANT_ID,
                        inventory_policy: 'deny',
                        position: 1,
                        price: retailPrice,
                        product_id: DEFAULT_ITEMS.SHOPIFY_PRODUCT_ID,
                        sku: null,
                        taxable: true,
                        title: 'Small',
                        updated_at: '2021-12-30T19:00:00-05:00',
                        option1: 'Small',
                        option2: null,
                        option3: null,
                        image_id: null,
                        inventory_item_id: null,
                        inventory_quantity: newInventory,
                        old_inventory_quantity: 75,
                    },
                ],
                options: [],
                images: [],
                image: null,
                media: [],
                variant_gids: [
                    {
                        admin_graphql_api_id: composeGid('ProductVariant', DEFAULT_ITEMS.SHOPIFY_VARIANT_ID),
                        updated_at: '2021-12-31T00:00:00.000Z',
                    },
                ],
            },
        },
    };
};

export const getRetailerProductUpdateEvent = (price: string, newInventory: number) => {
    return {
        version: '0',
        id: 'abcd1234-5678-90ef-gh12-3456789ijklm',
        'detail-type': 'Shopify Topic',
        source: 'shopify.com/webhooks',
        account: '123456789012',
        time: '2023-08-15T12:34:56Z',
        region: 'us-east-1',
        resources: [],
        detail: {
            'X-Shopify-Topic': 'products/update',
            'X-Shopify-Hmac-Sha256': 'hmac_value',
            'X-Shopify-Shop-Domain': 'example.myshopify.com',
            'X-Shopify-Webhook-Id': 'webhook_id',
            'X-Shopify-Triggered-At': '2024-08-15T12:34:56Z',
            'X-Shopify-Event-Id': 'event_id',
            payload: {
                admin_graphql_api_id: composeGid('Product', DEFAULT_ITEMS.IMPORTED_SHOPIFY_PRODUCT_ID),
                body_html: 'An example T-Shirt',
                created_at: null,
                handle: 'example-t-shirt',
                id: DEFAULT_ITEMS.IMPORTED_SHOPIFY_PRODUCT_ID,
                product_type: 'Shirts',
                published_at: '2021-12-31T19:00:00-05:00',
                template_suffix: null,
                title: 'Example T-Shirt',
                updated_at: '2021-12-31T19:00:00-05:00',
                vendor: 'Acme',
                status: 'active',
                published_scope: 'web',
                tags: 'example, mens, t-shirt',
                variants: [
                    {
                        admin_graphql_api_id: composeGid('ProductVariant', DEFAULT_ITEMS.IMPORTED_SHOPIFY_VARIANT_ID),
                        barcode: null,
                        compare_at_price: '24.99',
                        created_at: '2021-12-29T19:00:00-05:00',
                        id: DEFAULT_ITEMS.IMPORTED_SHOPIFY_VARIANT_ID,
                        inventory_policy: 'deny',
                        position: 1,
                        price: price,
                        product_id: DEFAULT_ITEMS.IMPORTED_SHOPIFY_PRODUCT_ID,
                        sku: null,
                        taxable: true,
                        title: 'Small',
                        updated_at: '2021-12-30T19:00:00-05:00',
                        option1: 'Small',
                        option2: null,
                        option3: null,
                        image_id: null,
                        inventory_item_id: null,
                        inventory_quantity: newInventory,
                        old_inventory_quantity: 75,
                    },
                ],
                options: [],
                images: [],
                image: null,
                media: [],
                variant_gids: [
                    {
                        admin_graphql_api_id: 'gid://shopify/ProductVariant/757650484644203962',
                        updated_at: '2022-01-01T00:00:00.000Z',
                    },
                    {
                        admin_graphql_api_id: 'gid://shopify/ProductVariant/642667041472713922',
                        updated_at: '2021-12-31T00:00:00.000Z',
                    },
                ],
            },
        },
    };
};
